Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"
  config.vm.box_version = "20260210.2384.0"
  config.vm.hostname = "debian13-amd64"

  # Avoid host-specific synced folder setup prompts (SMB/NFS) on macOS.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "qemu64"
    qe.smp = "2"
    qe.memory = "4096"
    qe.net_device = "virtio-net-pci"
    qe.ssh_port = 60022
    qe.qemu_dir = "/opt/homebrew/share/qemu"
    qe.extra_qemu_args = %w(-accel tcg,thread=multi,tb-size=512)
  end
end
